### ISSUE TITLE
Invalid behavior: :lt.plugins.tern/start-server - Light Table 0.8.0

### ISSUE THREAD

**Issue by Peeneye** [mortalapeman/LT-TernJS#23]
Light Table Version: 0.8.0
Platform: Windows x64
TernJS Version:  0.1.9 (According to Plugin Manager)

Fails with:
TypeError: Cannot read property 'call' of undefined at Function.__BEH__start_server
                  (ternjs_compiled.js:423:23)
                  ... bunch of bootstrap.js logs...
                 at Function.__BEH__try_send (ternjs_compiled.js:510:25)

I would really like to use this plugin on Light Table.  Let me know if you need any other info.

**Comment by mortalapeman** [comment]
I won't have a chance to look into this until Monday, but maybe @Armaklan will be able to check it out before then. Thanks for the ticket!

**Comment by Armaklan** [comment]
Sorry for the response time.
I am going to check it. Maybe i must change some code with lighttable 0.8.0

**Comment by Armaklan** [comment]
Last release is 0.1.10
Have you try this ?

**Comment by Armaklan** [comment]
I open an issue on LightTable repository : 
https://github.com/LightTable/LightTable/issues/2043

Plugin manager dont push the last version.
Please, try to install 1.0.10 manually.

**Comment by Armaklan** [comment]
Fix with last release of lighttable

**Comment by Peeneye** [comment]
Thank you!!  I'm going to check this out today.
