### ISSUE TITLE
Error: channel closed

### ISSUE THREAD

**Issue by ghachey** [mortalapeman/LT-TernJS#8]
Hi,

I don't know if this is expected behavior or not. When using the LT-TernJS plugin I constantly have the following error in my console.

```
Error channel closed
  at ChildProcess.target.send(child_process.js:402:26)
  at eval...
  ...
```

I have tried running it with the default behavior and also adding the following to my workspace.behaviors.

```
{:+ {:tern.config [(:lt.plugins.tern/libs :ecma5)
                   (:lt.plugins.tern/plugin :node true)]}
 :- {:tern.config [:lt.plugins.tern/libs :ecma5 :browser :jquery :underscore]}}
```

I get some form of auto-completion although it is very noisy and near useless in that form to me.

When I try the jump to definition feature I simply get a "Disconnected from Tern Javascript Server" message in the console and nothing happens.

When I try the in-line documentation feaure the same error happens: "Disconnected from Tern Javascript Server" and nothing happens.

I think I just don't get I to set it up properly or something.

**Comment by Mouvedia** [comment]
I am having the same problem with the dev branch.

```Error: channel closed
    at ChildProcess.target.send (child_process.js:402:26) …```
